shell /usr/bin/fish

include colors/yuka.conf

font_family      JetBrainsMono Nerd Font Mono
font_size        11

disable_ligatures yes
enable_audio_bell no

shell_integration enabled

cursor_shape     underline

url_style curly

remember_window_size  no
# initial_window_width  640
# initial_window_height 400
initial_window_width  78c
initial_window_height 23c
window_padding_width  15
cursor_blink_interval 0

background_opacity 0.80
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
confirm_os_window_close 0

# -- Performance settings
sync_to_monitor no

# -- Perf
repaint_delay    2
input_delay      1

cursor_trail 3
