`# Enable image previews
set preview_images true

# Set the rendering engine
# If you are using Kitty terminal:
set preview_images_method kitty

# If you are using Alacritty/Foot/WezTerm:
# set preview_images_method ueberzugpp

# Enable script previews for PDFs/Videos/Images
set use_preview_script true

# Default is usually 1,3,4. 
# To give the image preview dynamic MAX space, use 1,2,5 or 1,1,4:
set column_ratios 1,2,5

# 1. Copy full file PATH to Wayland clipboard (Press 'yc')
map yc shell echo -n %d/%f | wl-copy

# 2. Copy ACTUAL IMAGE DATA to Wayland clipboard (Press 'yi')
map yi shell wl-copy --type image/png < %s
