## name: Yuuka Dark (Waybar Sync)
## author: Custom
## license: MIT
## blurb: Ultra-dark palette matched to dark top bar and SwayNC panel

# The basic colors
foreground            #c6d0f5
background            #111116
selection_foreground  #111116
selection_background  #2a2b3d

# Cursor colors
cursor                #c6d0f5
cursor_text_color     #111116

# URL underline color when hovering with mouse
url_color             #81a1c1

# Kitty window border colors
active_border_color   #3b4252
inactive_border_color #181825
bell_border_color     #e5c07b

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #111116
active_tab_background   #81a1c1
inactive_tab_foreground #a6adc8
inactive_tab_background #181825
tab_bar_background      #111116

# Colors for marks (marked text in the terminal)
mark1_foreground #111116
mark1_background #81a1c1
mark2_foreground #111116
mark2_background #b48ead
mark3_foreground #111116
mark3_background #8fbcbb

# The 16 terminal colors

# black (deep black to match bar)
color0 #111116
color8 #45475a

# red (muted dark pastel red)
color1 #e06c75
color9 #e06c75

# green (muted soft sage)
color2 #a3be8c
color10 #a3be8c

# yellow (gold/amber)
color3 #e5c07b
color11 #e5c07b

# blue (desaturated steel blue)
color4 #81a1c1
color12 #81a1c1

# magenta (deep lavender)
color5 #b48ead
color13 #b48ead

# cyan (cool slate cyan)
color6 #8fbcbb
color14 #8fbcbb

# white (crisp readable text)
color7 #a6adc8
color15 #c6d0f5
